### view list
GET https://orderdesk.hstest-domain.ch/admin/webland/www/rest
Authorization: Basic Administrator 5522-tool

### view item
GET https://orderdesk.hstest-domain.ch/admin/webland/www/rest/22
Authorization: Basic Administrator 5522-tool

### show edit item
GET https://orderdesk.hstest-domain.ch/admin/webland/www/rest/22/edit
Authorization: Basic Administrator 5522-tool

### update item
PUT https://orderdesk.hstest-domain.ch/admin/webland/www/rest/22
Authorization: Basic Administrator 5522-tool
Content-Type: application/x-www-form-urlencoded

id=999&value=content

