name: Deploy
on:
  push:
    branches: [ "dev" ]
jobs:
  pullProject:
    runs-on: self-hosted
    steps:
    - name: Pull Project
      run: |
        cd /mnt/my-personal-data/work/www/test.localhost
        git pull origin dev